SELECT * 
FROM practice2.cleaned_retail_sales;

-- Which product categories generate the most revenue?
SELECT Category, SUM(`Total Spent`) AS Revenue
FROM practice2.cleaned_retail_sales
GROUP BY Category
ORDER BY Revenue DESC
LIMIT 10 ;


-- What are the top 10 best-selling products?
SELECT Item , sum(Quantity) as Total_Sold
FROM practice2.cleaned_retail_sales
GROUP BY Item 
ORDER BY Total_Sold ;

-- What is the average customer spending per transaction?
SELECT avg(`Total Spent`) AS average_spending
FROM practice2.cleaned_retail_sales;

-- Which customers spend the most money?
SELECT `Customer ID`,sum(`Total Spent`) AS Total_Spent
FROM practice2.cleaned_retail_sales
GROUP BY `Customer ID`
ORDER BY Total_Spent;

-- Are online or offline stores generating more revenue?
SELECT Location,sum(`Total Spent`) as more_revenue 
FROM practice2.cleaned_retail_sales
GROUP BY Location ;

-- What is the most popular payment method?
SELECT `Payment Method`, COUNT(*) Transactions
FROM practice2.cleaned_retail_sales
GROUP BY `Payment Method`
ORDER BY Transactions DESC;

-- Do discounts increase sales revenue?
SELECT `Discount Applied`,sum(`Total Spent`)as revenue
FROM practice2.cleaned_retail_sales
GROUP BY `Discount Applied`
ORDER BY revenue DESC ;


-- How many transactions had discounts?
SELECT `Discount Applied`, COUNT(`Transaction ID`) AS total_transaction
FROM practice2.cleaned_retail_sales
WHERE `Discount Applied`= 'YES'
GROUP BY `Discount Applied` ;

-- What are the monthly sales trends?
SELECT YEAR(`Transaction Date`)AS year ,
MONTH(`Transaction Date`) AS month, 
sum(`Total Spent`) as total_revenue
FROM practice2.cleaned_retail_sales
GROUP BY year,month
ORDER BY year,month  DESC ;

-- Which month has the highest sales?
SELECT MONTH(`Transaction Date`) AS month,count(`Transaction ID`) as Transaction
FROM  practice2.cleaned_retail_sales
GROUP BY month
ORDER BY Transaction DESC;

-- Which category sells the most quantity?
SELECT Category ,sum(Quantity) as Total_Quantity
FROM practice2.cleaned_retail_sales
GROUP BY Category
ORDER BY Total_Quantity DESC ;

-- Revenue generated by category and location
SELECT Category, Location,sum(`Total Spent`) as revenue
FROM practice2.cleaned_retail_sales
GROUP BY Category, Location
ORDER BY  revenue


